### ISSUE TITLE
Missing helm installation options documentations

### ISSUE THREAD

**Issue by nashtsai** [apecloud/kubeblocks.io#65]
Missing helm installation options documentation.

FYR:

https://kubevela.net/docs/installation/kubernetes

![image](https://user-images.githubusercontent.com/285407/232494441-38d5d76b-0bf5-434f-8a23-23fd3f1093a2.png)

**Comment by sailwebs** [comment]
https://kubeblocks.io/docs/release-0.6/user_docs/installation/install-with-helm/install-kubeblocks-with-helm
