### ISSUE TITLE
kbcli install options should be tabbed with a number of OS/pkg manager  installation guides

### ISSUE THREAD

**Issue by nashtsai** [apecloud/kubeblocks.io#66]
kbcli install options should be tabbed with a number of OS/pkg manager  installation guides.

FYR:

https://kubevela.net/docs/installation/kubernetes

![image](https://user-images.githubusercontent.com/285407/232495518-882902a3-16a0-4934-8a16-b3691b0c474a.png)

**Comment by michelle-0808** [comment]
Done.
https://kubeblocks.io/docs/preview/user_docs/installation/install-with-kbcli/install-kbcli
